In [1]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt


In [15]:
df=pd.read_csv(r"C:\Users\BHOOMISH\OneDrive\Desktop\HeartDisease.csv")
df


age  gender  chest_pain  rest_bps  cholestrol  fasting_blood_sugar  \
0     63       1           3       145         233                    1   
1     37       1           2       130         250                    0   
2     41       0           1       130         204                    0   
3     56       1           1       120         236                    0   
4     57       0           0       120         354                    0   
..   ...     ...         ...       ...         ...                  ...   
298   57       0           0       140         241                    0   
299   45       1           3       110         264                    0   
300   68       1           0       144         193                    1   
301   57       1           0       130         131                    0   
302   57       0           1       130         236                    0   

     rest_ecg  thalach  exer_angina  old_peak  slope  ca  thalassemia  target  
0           0      150            0       2.3      0   0            1       1  
1           1      187            0       3.5      0   0            2       1  
2           0      172            0       1.4      2   0            2       1  
3           1      178            0       0.8      2   0            2       1  
4           1      163            1       0.6      2   0            2       1  
..        ...      ...          ...       ...    ...  ..          ...     ...  
298         1      123            1       0.2      1   0            3       0  
299         1      132            0       1.2      1   0            3       0  
300         1      141            0       3.4      1   2            3       0  
301         1      115            1       1.2      1   1            3       0  
302         0      174            0       0.0      1   1            2       0  

[303 rows x 14 columns]

In [28]:
x=df.iloc[:,0:13]
y=df.iloc[:,-1]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train.shape

(242, 13)

In [30]:
from sklearn.tree import DecisionTreeClassifier

In [32]:
tree=DecisionTreeClassifier()
tree

DecisionTreeClassifier()

In [35]:
tree.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': None,
 'splitter': 'best'}

In [36]:
tree.fit(x_train,y_train)

DecisionTreeClassifier()

In [39]:
y_prediction=tree.predict(x_test)

In [41]:
from sklearn.metrics import confusion_matrix

In [44]:
print(confusion_matrix(y_test,y_prediction)) #TP - 26 , TN - 21 , FP - 3 , FN - 11

[[26  3]
 [11 21]]


In [46]:
from sklearn.metrics import classification_report

In [47]:
print(classification_report(y_test,y_prediction))

              precision    recall  f1-score   support

           0       0.70      0.90      0.79        29
           1       0.88      0.66      0.75        32

    accuracy                           0.77        61
   macro avg       0.79      0.78      0.77        61
weighted avg       0.79      0.77      0.77        61



In [52]:
tree.feature_importances_

array([0.10812579, 0.04101489, 0.2252627 , 0.06377351, 0.0918243 ,
       0.01669311, 0.02861676, 0.05325505, 0.07542094, 0.10074824,
       0.027316  , 0.12960636, 0.03834236])

In [58]:
tree2=DecisionTreeClassifier(criterion="entropy",ccp_alpha=0.04)
tree2

DecisionTreeClassifier(ccp_alpha=0.04, criterion='entropy')

In [59]:
tree2.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.04, criterion='entropy')

In [61]:
y_prediction2=tree2.predict(x_test)

In [63]:
print(confusion_matrix(y_test,y_prediction))

[[26  3]
 [11 21]]


In [62]:
print(classification_report(y_test,y_prediction2))

              precision    recall  f1-score   support

           0       0.75      0.83      0.79        29
           1       0.83      0.75      0.79        32

    accuracy                           0.79        61
   macro avg       0.79      0.79      0.79        61
weighted avg       0.79      0.79      0.79        61

